version: "2.3"

volumes:
  front-build: {}
  server-static: {}
  mysql-data: {}

services:
  # to build DB
  mysql: 
    # platform: linux/x86_64
    image: mysql:8.0.23
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment: 
        MYSQL_DATABASE: ${DJANGO_DB_NAME}
        MYSQL_ROOT_PASSWORD: ${DJANGO_DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  # to build backend
  backend:
    build:
        context: ./backend
    image: praivacy_policy_app_backend
    restart: unless-stopped
    environment:
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_DB_USER: ${DJANGO_DB_USER}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}
      DJANGO_DB_HOST: ${DJANGO_DB_HOST}
      DJANGO_DB_PORT: ${DJANGO_DB_PORT}
    expose:
        - "8000"
    volumes:
        - server-static:/app/static

  # to build front
  frontend:
    build:
        context: ./frontend
    image:  praivacy_policy_app_frontend
    restart: on-failure
    volumes:
        - front-build:/front/build

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - server-static:/server-static
        - front-build:/front-build
    ports:
        - 80:80
        - 443:443
    depends_on:
        - backend
        - frontend