# Generated by Django 3.2 on 2021-07-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_studio_member',
            field=models.BooleanField(default=False, verbose_name='Studio member'),
        ),
    ]
