version: "2.3"

volumes:
  front-build: {}
  server-static: {}
  server-media: {}
  mysql-data: {}

services:
  # to build DB
  mysql: 
    platform: linux/x86_64
    image: mysql:8.0.23
    restart: always
    environment: 
        MYSQL_DATABASE: ${DJANGO_DB_NAME}
        MYSQL_ROOT_PASSWORD: ${DJANGO_DB_PASSWORD}
        LANG: C.UTF_8
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - mysql-data:/var/lib/mysql

  # to build backend
  backend:
    build:
        context: ../backend
    image: praivacy_policy_app_backend
    restart: unless-stopped
    environment:
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_DB_USER: ${DJANGO_DB_USER}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}
      DJANGO_DB_HOST: ${DJANGO_DB_HOST}
      DJANGO_DB_PORT: ${DJANGO_DB_PORT}
    expose:
        - "8000"
    volumes:
        - server-static:/app/static
        - server-media:/app/media

  # to build front
  frontend:
    build:
        context: ../frontend
    image:  praivacy_policy_app_frontend
    restart: on-failure
    volumes:
        - front-build:/front/build