# Generated by Django 3.2 on 2021-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicyform',
            name='age',
        ),
        migrations.AddField(
            model_name='privacypolicyform',
            name='birthday',
            field=models.CharField(default='', max_length=8, verbose_name='Birthday'),
        ),
    ]
