# Generated by Django 3.2 on 2021-05-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210522_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicyform',
            name='birthday',
            field=models.CharField(default='', max_length=16, verbose_name='Birthday'),
        ),
    ]
