# Generated by Django 3.2 on 2021-05-24 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_privacypolicyform_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='psd/', verbose_name='PSD image')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.privacypolicyform')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
